---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template provisions the JJTech Network Infrastructure
Metadata: {}
Parameters: {}
Mappings: {}
Conditions: {}
Resources:
  JJTechVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: JJTechVPC
Outputs: {}